### ISSUE TITLE
Provide a complete SHA256 project

### ISSUE THREAD

**Issue by suilin1254703825** [LekKit/sha256#1]
Your sha256 's API implementation is awesome, thank you very much.
 It would be even better to provide a complete project。

**Comment by LekKit** [comment]
Okay, i am not so sure what you mean by "complete project", but here you are:
I added a file hashing example and test vectors in commit [e74f8c2](https://github.com/LekKit/sha256/commit/e74f8c2a44366cf5186c025a5d221615ec1a8642), hope that helps :D
It passes all the tests taken from multiple sources, so the library is fully standard-compliant

**Comment by suilin1254703825** [comment]
Thank you for your update.
